Repository lblod/app-mow-registry, pull requests merged in 2024-07, with the labels that each got.

#75 GN-4788: Data Model Migration to OSLO Compliance
  config/authorization/config.ex
  config/dispatcher/dispatcher.ex
  config/migrations/20240429115806-migration-to-oslo-template.sparql
  config/migrations/20240429132129-migration-to-oslo-traffic-measure-concept.sparql
  config/migrations/20240502140944-migrate-to-oslo-traffic-sign-concept.sparql
  config/migrations/20240529140507-insert-shapes.sparql
  config/migrations/20240605153446-add-document-type-to-images.sparql
  config/migrations/20240710111854-migrate-temporal-to-variablesignage.sparql
  config/resources/domain.json
  config/resources/domain.lisp
  docker-compose.yml
Labels: enhancement

#78 Update mu-file-service to version 3.4.0
  docker-compose.yml
Labels: internal

#79 Add Icon resource
  config/authorization/config.ex
  config/dispatcher/dispatcher.ex
  config/resources/domain.json
Labels: enhancement

#82 Fix skosConcepts inScheme cardinality
  config/resources/domain.json
Labels: bug

#81 Replace mappings resource with variable
  config/authorization/config.ex
  config/dispatcher/dispatcher.ex
  config/migrations/20240730174403-mapping-to-variable.sparql
  config/resources/domain.json
Labels: enhancement
